version: "3.7"
services:
  parachain:
    ports:
      - 9944:9944
      - 9933:9933
    volumes:
      - parachain:/acala/data
    build:
      context: .
      dockerfile: parachain.Dockerfile
    command:
      - --base-path=/acala/data
      - --chain=/app/karura-latest-2000.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --collator
      - --rpc-methods=unsafe
      - --wasm-execution=compiled
      - --execution=wasm
      - --
      - --chain=/app/rococo-local.json
      - --wasm-execution=compiled
      - --execution=wasm
      - --no-beefy
    environment:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug,parachain::collator-protocol
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
volumes:
  parachain:
